Fix auto-completion of partial key name in key/value configurations
Previously either a field or a quoted field string was passed into
value_conditions, causing the following error when expanding
auto-complete values for partial keys:

    NoMethodError:
      undefined method `quoted_field' for "\"keys\".\"name\"":String
    # ./lib/scoped_search/auto_complete_builder.rb:266:in `value_conditions'
    # ./lib/scoped_search/auto_complete_builder.rb:178:in `complete_key'